apiVersion: v1
kind: ConfigMap
metadata:
  name: authorization-policies
  namespace: nexus-auth
data:
  rbac-policies.json: |
    {
      "policies": [
        {
          "name": "Admin Full Access",
          "description": "Full system access for administrators",
          "type": "role",
          "logic": "POSITIVE",
          "decisionStrategy": "UNANIMOUS",
          "config": {
            "roles": "[{\"id\":\"admin\",\"required\":true}]"
          }
        },
        {
          "name": "Architect Access",
          "description": "Architectural analysis and design access",
          "type": "role", 
          "logic": "POSITIVE",
          "decisionStrategy": "UNANIMOUS",
          "config": {
            "roles": "[{\"id\":\"architect\",\"required\":true},{\"id\":\"admin\",\"required\":false}]"
          }
        },
        {
          "name": "Developer Access",
          "description": "Development tools and code analysis access",
          "type": "role",
          "logic": "POSITIVE", 
          "decisionStrategy": "UNANIMOUS",
          "config": {
            "roles": "[{\"id\":\"developer\",\"required\":true},{\"id\":\"architect\",\"required\":false},{\"id\":\"admin\",\"required\":false}]"
          }
        },
        {
          "name": "Project Manager Access",
          "description": "Project management and reporting access",
          "type": "role",
          "logic": "POSITIVE",
          "decisionStrategy": "UNANIMOUS", 
          "config": {
            "roles": "[{\"id\":\"project_manager\",\"required\":true},{\"id\":\"admin\",\"required\":false}]"
          }
        },
        {
          "name": "Executive Access",
          "description": "Executive dashboards and strategic insights",
          "type": "role",
          "logic": "POSITIVE",
          "decisionStrategy": "UNANIMOUS",
          "config": {
            "roles": "[{\"id\":\"executive\",\"required\":true},{\"id\":\"admin\",\"required\":false}]"
          }
        },
        {
          "name": "Read Only Access",
          "description": "Read-only access to system information",
          "type": "role",
          "logic": "POSITIVE",
          "decisionStrategy": "UNANIMOUS",
          "config": {
            "roles": "[{\"id\":\"viewer\",\"required\":true}]"
          }
        }
      ],
      "resources": [
        {
          "name": "AI Chat Interface",
          "type": "urn:nexus:resource:chat",
          "ownerManagedAccess": false,
          "attributes": {},
          "uris": ["/api/v1/chat/*", "/api/v1/conversation/*"],
          "scopes": [
            {"name": "read"},
            {"name": "write"},
            {"name": "delete"}
          ]
        },
        {
          "name": "Code Analysis",
          "type": "urn:nexus:resource:code",
          "ownerManagedAccess": false,
          "attributes": {},
          "uris": ["/api/v1/code/*", "/api/v1/analysis/*"],
          "scopes": [
            {"name": "read"},
            {"name": "analyze"},
            {"name": "modify"}
          ]
        },
        {
          "name": "Architecture Design",
          "type": "urn:nexus:resource:architecture",
          "ownerManagedAccess": false,
          "attributes": {},
          "uris": ["/api/v1/architecture/*", "/api/v1/design/*"],
          "scopes": [
            {"name": "read"},
            {"name": "design"},
            {"name": "approve"}
          ]
        },
        {
          "name": "Project Management",
          "type": "urn:nexus:resource:project",
          "ownerManagedAccess": false,
          "attributes": {},
          "uris": ["/api/v1/projects/*", "/api/v1/tasks/*"],
          "scopes": [
            {"name": "read"},
            {"name": "write"},
            {"name": "manage"}
          ]
        },
        {
          "name": "Executive Dashboard",
          "type": "urn:nexus:resource:executive",
          "ownerManagedAccess": false,
          "attributes": {},
          "uris": ["/api/v1/executive/*", "/api/v1/metrics/*"],
          "scopes": [
            {"name": "read"},
            {"name": "export"}
          ]
        },
        {
          "name": "System Administration",
          "type": "urn:nexus:resource:admin",
          "ownerManagedAccess": false,
          "attributes": {},
          "uris": ["/api/v1/admin/*", "/api/v1/users/*", "/api/v1/config/*"],
          "scopes": [
            {"name": "read"},
            {"name": "write"},
            {"name": "delete"},
            {"name": "configure"}
          ]
        }
      ],
      "permissions": [
        {
          "name": "Admin Full Permission",
          "type": "resource",
          "logic": "POSITIVE",
          "decisionStrategy": "UNANIMOUS",
          "resources": ["System Administration"],
          "policies": ["Admin Full Access"]
        },
        {
          "name": "Architect Design Permission",
          "type": "resource",
          "logic": "POSITIVE", 
          "decisionStrategy": "UNANIMOUS",
          "resources": ["Architecture Design", "Code Analysis"],
          "policies": ["Architect Access"]
        },
        {
          "name": "Developer Code Permission",
          "type": "resource",
          "logic": "POSITIVE",
          "decisionStrategy": "UNANIMOUS", 
          "resources": ["Code Analysis", "AI Chat Interface"],
          "policies": ["Developer Access"]
        },
        {
          "name": "Project Manager Permission",
          "type": "resource",
          "logic": "POSITIVE",
          "decisionStrategy": "UNANIMOUS",
          "resources": ["Project Management", "AI Chat Interface"],
          "policies": ["Project Manager Access"]
        },
        {
          "name": "Executive Dashboard Permission",
          "type": "resource",
          "logic": "POSITIVE",
          "decisionStrategy": "UNANIMOUS",
          "resources": ["Executive Dashboard", "AI Chat Interface"],
          "policies": ["Executive Access"]
        },
        {
          "name": "Viewer Read Permission",
          "type": "scope",
          "logic": "POSITIVE",
          "decisionStrategy": "UNANIMOUS",
          "scopes": ["read"],
          "policies": ["Read Only Access"]
        }
      ]
    }
  
  kong-rbac-plugin.yaml: |
    apiVersion: configuration.konghq.com/v1
    kind: KongPlugin
    metadata:
      name: nexus-rbac
      namespace: nexus-gateway
    config:
      anonymous: ""
      claims_to_verify:
        - exp
        - iat
        - iss
        - aud
      cookie_names: []
      header_names:
        - authorization
      key_claim_name: iss
      maximum_expiration: 0
      run_on_preflight: true
      secret_is_base64: false
      uri_param_names: []
    plugin: jwt
    
  kong-rate-limit.yaml: |
    apiVersion: configuration.konghq.com/v1
    kind: KongPlugin
    metadata:
      name: nexus-rate-limit
      namespace: nexus-gateway
    config:
      minute: 1000
      hour: 10000
      day: 100000
      policy: redis
      redis_host: redis-cluster.nexus-infrastructure
      redis_port: 6379
      redis_timeout: 2000
      hide_client_headers: false
    plugin: rate-limiting
    
  kong-cors.yaml: |
    apiVersion: configuration.konghq.com/v1
    kind: KongPlugin
    metadata:
      name: nexus-cors
      namespace: nexus-gateway
    config:
      origins:
        - "https://app.nexus-architect.local"
        - "http://localhost:3000"
        - "http://localhost:8080"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - Authorization
        - X-Auth-Token
      exposed_headers:
        - X-Auth-Token
        - X-RateLimit-Limit
        - X-RateLimit-Remaining
        - X-RateLimit-Reset
      credentials: true
      max_age: 3600
      preflight_continue: false
    plugin: cors
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-auth-service
  namespace: nexus-gateway
  annotations:
    konghq.com/plugins: nexus-rbac,nexus-rate-limit,nexus-cors
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000
  selector:
    app: nexus-api
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: nexus-auth-ingress
  namespace: nexus-gateway
route:
  methods:
  - GET
  - POST
  - PUT
  - DELETE
  - PATCH
  - OPTIONS
  regex_priority: 0
  strip_path: false
  preserve_host: true
  protocols:
  - http
  - https
upstream:
  algorithm: round-robin
  hash_on: none
  hash_fallback: none
  healthchecks:
    active:
      healthy:
        interval: 0
        successes: 0
      unhealthy:
        interval: 0
        tcp_failures: 0
        timeouts: 0
        http_failures: 0
    passive:
      healthy:
        successes: 0
      unhealthy:
        tcp_failures: 0
        timeouts: 0
        http_failures: 0
proxy:
  protocol: http
  path: /
  connect_timeout: 60000
  retries: 5
  read_timeout: 60000
  write_timeout: 60000

